import { internalMutation } from "./_generated/server";

export const seedMenu = internalMutation({
  args: {},
  handler: async (ctx) => {
    // Check if data already exists
    const existing = await ctx.db.query("menuItems").take(1);
    if (existing.length > 0) {
      return "Menu already seeded";
    }

    const items = [
      // SHAWARMA
      {
        name: "Classic Chicken Shawarma",
        arabicName: "شاورما دجاج كلاسيكية",
        description:
          "Tender marinated chicken, pickled turnips, garlic sauce, fresh vegetables, wrapped in warm bread.",
        price: 899,
        category: "shawarma" as const,
        tags: ["POPULAR"],
        isSpicy: false,
        isSignature: false,
        isAvailable: true,
        sortOrder: 1,
        displayIndex: "001",
      },
      {
        name: "Jakob's Signature Shawarma",
        arabicName: "شاورما جاكوب المميزة",
        description:
          "Our house special. Double-stacked chicken and lamb with secret spice blend, tahini, and house pickles.",
        price: 1299,
        category: "shawarma" as const,
        tags: ["SIGNATURE", "POPULAR"],
        isSpicy: false,
        isSignature: true,
        isAvailable: true,
        sortOrder: 2,
        displayIndex: "002",
      },
      {
        name: "Lamb Shawarma",
        arabicName: "شاورما لحم",
        description:
          "Slow-roasted lamb shoulder, sumac onions, tahini sauce, and fresh herbs.",
        price: 1099,
        category: "shawarma" as const,
        tags: [],
        isSpicy: false,
        isSignature: false,
        isAvailable: true,
        sortOrder: 3,
        displayIndex: "003",
      },
      {
        name: "Spicy Chicken Shawarma",
        arabicName: "شاورما دجاج حارة",
        description:
          "Fire-kissed chicken with harissa, chili flakes, pickled jalapenos, and cooling yogurt.",
        price: 999,
        category: "shawarma" as const,
        tags: ["HOT"],
        isSpicy: true,
        isSignature: false,
        isAvailable: true,
        sortOrder: 4,
        displayIndex: "004",
      },
      {
        name: "Mixed Shawarma Plate",
        arabicName: "صحن شاورما مشكل",
        description:
          "Generous portions of both chicken and lamb shawarma served on a bed of rice with all the fixings.",
        price: 1499,
        category: "shawarma" as const,
        tags: ["POPULAR"],
        isSpicy: false,
        isSignature: false,
        isAvailable: true,
        sortOrder: 5,
        displayIndex: "005",
      },
      {
        name: "Veggie Shawarma",
        arabicName: "شاورما خضار",
        description:
          "Roasted cauliflower and eggplant with za'atar, tahini, and pickled vegetables.",
        price: 799,
        category: "shawarma" as const,
        tags: ["VEGGIE"],
        isSpicy: false,
        isSignature: false,
        isAvailable: true,
        sortOrder: 6,
        displayIndex: "006",
      },
      // DONER
      {
        name: "Classic Doner Kebab",
        arabicName: "دونر كباب كلاسيكي",
        description:
          "Thinly sliced rotisserie meat in fresh bread with crisp salad and garlic-yogurt sauce.",
        price: 849,
        category: "doner" as const,
        tags: ["POPULAR"],
        isSpicy: false,
        isSignature: false,
        isAvailable: true,
        sortOrder: 1,
        displayIndex: "007",
      },
      {
        name: "Iskender Doner",
        arabicName: "إسكندر دونر",
        description:
          "Sliced doner over torn bread, doused in tomato butter sauce and yogurt. A Turkish classic.",
        price: 1399,
        category: "doner" as const,
        tags: ["SIGNATURE"],
        isSpicy: false,
        isSignature: true,
        isAvailable: true,
        sortOrder: 2,
        displayIndex: "008",
      },
      {
        name: "Doner Box",
        arabicName: "صندوق دونر",
        description:
          "Doner meat over fries with your choice of sauce. Simple, satisfying, legendary.",
        price: 999,
        category: "doner" as const,
        tags: ["POPULAR"],
        isSpicy: false,
        isSignature: false,
        isAvailable: true,
        sortOrder: 3,
        displayIndex: "009",
      },
      {
        name: "Spicy Doner Wrap",
        arabicName: "لفة دونر حارة",
        description:
          "Doner in a lavash wrap with hot sauce, jalapenos, and crunchy slaw.",
        price: 949,
        category: "doner" as const,
        tags: ["HOT"],
        isSpicy: true,
        isSignature: false,
        isAvailable: true,
        sortOrder: 4,
        displayIndex: "010",
      },
      // SIDES
      {
        name: "Hummus",
        arabicName: "حمص",
        description: "Creamy chickpea dip with olive oil and paprika.",
        price: 449,
        category: "sides" as const,
        tags: ["VEGGIE"],
        isSpicy: false,
        isSignature: false,
        isAvailable: true,
        sortOrder: 1,
        displayIndex: "011",
      },
      {
        name: "Falafel (6 pcs)",
        arabicName: "فلافل",
        description: "Crispy herb-packed chickpea fritters with tahini dip.",
        price: 549,
        category: "sides" as const,
        tags: ["VEGGIE", "POPULAR"],
        isSpicy: false,
        isSignature: false,
        isAvailable: true,
        sortOrder: 2,
        displayIndex: "012",
      },
      {
        name: "Fattoush Salad",
        arabicName: "فتوش",
        description:
          "Crispy pita, fresh vegetables, sumac, and pomegranate dressing.",
        price: 599,
        category: "sides" as const,
        tags: ["VEGGIE"],
        isSpicy: false,
        isSignature: false,
        isAvailable: true,
        sortOrder: 3,
        displayIndex: "013",
      },
      {
        name: "Loaded Fries",
        arabicName: "بطاطس محملة",
        description: "Crispy fries topped with garlic sauce, chili, and herbs.",
        price: 499,
        category: "sides" as const,
        tags: [],
        isSpicy: false,
        isSignature: false,
        isAvailable: true,
        sortOrder: 4,
        displayIndex: "014",
      },
      {
        name: "Tabbouleh",
        arabicName: "تبولة",
        description: "Fresh parsley, bulgur, tomato, and lemon juice.",
        price: 499,
        category: "sides" as const,
        tags: ["VEGGIE"],
        isSpicy: false,
        isSignature: false,
        isAvailable: true,
        sortOrder: 5,
        displayIndex: "015",
      },
      // DRINKS
      {
        name: "Ayran",
        arabicName: "عيران",
        description: "Traditional salted yogurt drink.",
        price: 299,
        category: "drinks" as const,
        tags: [],
        isSpicy: false,
        isSignature: false,
        isAvailable: true,
        sortOrder: 1,
        displayIndex: "016",
      },
      {
        name: "Fresh Mint Lemonade",
        arabicName: "ليمونادة بالنعناع",
        description: "Hand-squeezed lemonade with fresh mint leaves.",
        price: 399,
        category: "drinks" as const,
        tags: ["POPULAR"],
        isSpicy: false,
        isSignature: false,
        isAvailable: true,
        sortOrder: 2,
        displayIndex: "017",
      },
      {
        name: "Turkish Tea",
        arabicName: "شاي تركي",
        description: "Strong black tea served in a traditional tulip glass.",
        price: 249,
        category: "drinks" as const,
        tags: [],
        isSpicy: false,
        isSignature: false,
        isAvailable: true,
        sortOrder: 3,
        displayIndex: "018",
      },
      {
        name: "Sparkling Water",
        description: "Chilled sparkling mineral water.",
        price: 199,
        category: "drinks" as const,
        tags: [],
        isSpicy: false,
        isSignature: false,
        isAvailable: true,
        sortOrder: 4,
        displayIndex: "019",
      },
      // EXTRAS
      {
        name: "Extra Garlic Sauce",
        arabicName: "صوص ثوم إضافي",
        description: "Our house-made garlic sauce on the side.",
        price: 99,
        category: "extras" as const,
        tags: [],
        isSpicy: false,
        isSignature: false,
        isAvailable: true,
        sortOrder: 1,
        displayIndex: "020",
      },
      {
        name: "Extra Meat",
        arabicName: "لحم إضافي",
        description: "Double up on your protein.",
        price: 349,
        category: "extras" as const,
        tags: [],
        isSpicy: false,
        isSignature: false,
        isAvailable: true,
        sortOrder: 2,
        displayIndex: "021",
      },
      {
        name: "Pickled Turnips",
        arabicName: "لفت مخلل",
        description: "Tangy pink pickled turnips.",
        price: 149,
        category: "extras" as const,
        tags: ["VEGGIE"],
        isSpicy: false,
        isSignature: false,
        isAvailable: true,
        sortOrder: 3,
        displayIndex: "022",
      },
    ];

    for (const item of items) {
      await ctx.db.insert("menuItems", item);
    }

    return "Menu seeded with " + items.length + " items";
  },
});
